### ISSUE TITLE
SGS7 Edge Focus issues 

### ISSUE THREAD

**Issue by skryshtafovych** [PDF417/pdf417-android#18]
After updating to 5.5.2 users began to experience focus issues on their samsung devices.Our call center has received several calls about users being on Samsung S6 or S7 as-well as if we look at playstore most of bad comment are about focus issues from Samsung Devices.

**Comment by DoDoENT** [comment]
Hi, please update to latest version (5.2.2 is rather old version). The 5.5.1 version contains autofocus improvement for autofocus on Galaxy S6 and Galaxy S7 devices. Other devices (both Samsung and non-Samsung were not affected with this improvement).

**Comment by skryshtafovych** [comment]
Sorry that was a Typo our Gralel Build
**com.microblink:pdf417.mobi:5.5.2**

**Comment by DoDoENT** [comment]
Can you reproduce the issue with our demo app? On our side we get much more robust autofocus performance on S6 and S7 since version 5.5.1 (which included autofocus improvement).

Please note that PDF417 SDK does not have its own autofocus algorithm, instead it uses default provided by device camera. The trick in version 5.5.1 and later was in enabling phase autofocus which is not part of standard android API, but is supported on S6 and S7, whilst not enabled by default (unlike on other devices, like LG G5). We [raised that issue with Samsung](http://developer.samsung.com/forum/thread/continuous-autofocus-issues-with-samsung-galaxy-s6/201/289824?boardName=SDK&startId=zzzzz~), but so far they weren't helpful with resolving that issue.

**Comment by DoDoENT** [comment]
Does the problem persist with version [v6.1.0](https://github.com/PDF417/pdf417-android/releases/tag/v6.1.0)?

**Comment by skryshtafovych** [comment]
v6.0.1  had fixed the issue. Now with release of **Nougat**  has caused some new issues attached is where the app crashes and many users have complained about scanner not working at all.
[crashes.txt](https://github.com/PDF417/pdf417-android/files/804802/crashes.txt)
https://play.google.com/store/apps/details?id=gov.ca.lot.caLotteryApp

**Comment by DoDoENT** [comment]
HI @skryshtafovych - is the crash only happening only on SGS7 Edge with Android N? We cannot reproduce it on other Android N devices (Nexus 5X, OnePlus 3 and Motorola MotoZ).

**Comment by skryshtafovych** [comment]
@DoDoENT Its mainly happening on Samsung Devices 
![image](https://cloud.githubusercontent.com/assets/4966220/23378076/f29c1954-fce6-11e6-8215-56cbaf22905b.png)
![image](https://cloud.githubusercontent.com/assets/4966220/23378123/26cfa7fe-fce7-11e6-9db9-afb50233b4e1.png)

**Comment by DoDoENT** [comment]
Hi @skryshtafovych, thank you for the info. The autofocus issue should already be fixed in our internal codebase, but we haven't been able to reproduce the crash. However, we added some nullpointer checks based stack traces you've sent, but we still cannot gurantee that to be crash-free (the np checks weren't there in the first place because the callbacks in question should not be called more than once by a device camera - however it appears that on Android 7, Samsung devices do that).

We will try to push the bugfix release ASAP.

**Comment by DoDoENT** [comment]
Hi @skryshtafovych,

we released [v6.2.0](https://github.com/PDF417/pdf417-android/releases/tag/v6.2.0). Please try with it. As I already said, autofocus fixes for Android 7 Samsung devices should work (we tested with our [other app](https://play.google.com/store/apps/details?id=com.microblink.photomath), which has US-based users - we have only European versions of Samsung devices in the office which always worked correctly). For the crashes, I've added some null pointer checks, but I cannot guarantee that it will be completely crash-free (I couldn't reproduce the crash even before the "fix"). Please close this issue if it is solved for you now.

**Comment by skryshtafovych** [comment]
I have tried 6.2.0 and it seems like i am still experiencing  focus issues  on these devices an when scanner works it does not scan correctly many times returning invalid scan results.The google [doc](https://docs.google.com/document/d/1nvQ-srRQkZQ4o5XNJ9Q9cR6qZmzeA1CEn-aw824AucM/edit?usp=sharing).where length =0 meaning we got scan results back.

**Comment by DoDoENT** [comment]
What exact issues are you experiencing? What are _invalid scan results_? I've tried scanning barcodes from linked google doc and they can be scanned without any problems (using the latest SDK).

As I said earlier, in v6.2.0 we disabled PhaseAutofocus feature on Samsung devices. The PhaseAutofocus is a non-standard feature available only when using official Samsung Camera SDK for camera management and enables much faster and more accurate autofocus. However, it appears that this feature, when used from SDK, does not work on US versions of Samsung S7 devices (it works on european and international versions) - instead of making focus much faster and more accurate, it does not focus at all. As a workaround, we disabled that feature and rely on default Android camera API for performing camera focus, which on Samsung works (at least it can focus).

In our development builds, we tried with the latest version of Samsung camera SDK and even with their official demo app, there are autofocus problems when PhaseAutofocus is enabled, and when it is not, focus works the same as with default camera API. On non-US versions of S7 and S7 edge PhaseAutofocus works correctly both with our SDK and with Samsung's official camera SDK.

The focusing problem is obviously related to Samsung devices, as their camera driver seems to be broken on firmwares shipped by some US providers, such as AT&T, T-Com and Verizon. This is something we cannot fix, as we do not have the source code of their firmware. We can only workaround the bugs in their firmware - which we have done in v6.2.0.

We even contacted Samsung about that issue and they only told us not to hold the device less than 15 cm away from object camera is focusing on - which is not very helpful.
